name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x, 24.x]

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Type check
      run: pnpm typecheck

    - name: Test
      run: pnpm test

    - name: Build
      run: pnpm build

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-chrome-${{ matrix.node-version }}-${{ github.sha }}
        path: ./.output/chrome-mv3/

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-firefox-${{ matrix.node-version }}-${{ github.sha }}
        path: ./.output/firefox-mv2/

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-edge-${{ matrix.node-version }}-${{ github.sha }}
        path: ./.output/edge-mv3/
