name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26, 24]

    steps:
    - uses: actions/checkout@v7

    - uses: pnpm/setup@v1
      with:
        runtime: node@${{ matrix.node-version }}
        cache: true
        install: false

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Type check
      run: pnpm typecheck

    - name: Build
      run: pnpm build

    - name: Test
      run: pnpm test

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-chrome-${{ matrix.node-version }}-${{ github.sha }}
        path: ./.output/chrome-mv3/

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-firefox-${{ matrix.node-version }}-${{ github.sha }}
        path: ./.output/firefox-mv2/

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-edge-${{ matrix.node-version }}-${{ github.sha }}
        path: ./.output/edge-mv3/
